cmd/brew-services.rb

Resolves #6 
This change makes the assumption that the status of all of the services listed can be checked via the existence of plist files.  If services are only managed by `brew services` this should be a safe assumption.
I've removed the PID column because PID isn't available for all running services through `launchctl`, since it only returns services owned by the current user. Formula names may not match up to the command that's run (e.g. mysql => mysqld, php56 => php-fpm), so checking via `ps` would probably require parsing the plist file.
I'm not sure when the 'stale' and 'unknown' states would have occurred previously.
In order to detect 'unknown' again, any values in `ServicesCli.running` but not in `Formula.installed` would need to be added to the output; however …

List all services available to control

---

README.md
cmd/brew-services.rb

Hi,
This is an extended version of #27, allowing to act on `--all` services when running `start`, `stop` or `restart`.

Act on all services

---

cmd/brew-services.rb

Reverts Homebrew/homebrew-services#39

Revert "Invert logic for adding UserName to plist when running as root or not"

---

cmd/brew-services.rb

Use Formula#plist instead of Formula#startup_plist

---

cmd/brew-services.rb

These prompt the `brew services` start message from Homebrew but this command then fails. We could make Homebrew specify the full path but why specify extra arguments if they aren't necessary?
Closes https://github.com/Homebrew/homebrew-core/issues/1136.

Find Keg plists with non-default names.

---

cmd/brew-services.rb

brew-services: handle invalid keg.

---

cmd/brew-services.rb

This applies the fix from #56 
Fixes #56

Fixed error when starting service using OS X 10.11.5

---

cmd/brew-services.rb

Use Homebrew's new way of handling `--help` for external commands.

brew-services: use new Homebrew `--help`.

---

cmd/brew-services.rb

Use the Homebrew Rubocop style.

Rubocop tweaks.

---

cmd/brew-services.rb

Otherwise, don't try to start it.
Fixes #84.

Check if a formula is installed.

---

cmd/brew-services.rb

Hi,
I've stumbled across a case when `postgresql` would report being started successfully, but won't have a running process. It turned out that `launchctl` wasn't receiving the error code on `load`, but `list` revealed a non-zero exit code.
With this change in place it will mark services that aren't actually running, although they are loaded.

Detect service error

---

.travis.yml
README.md
cmd/brew-services.rb
completions/zsh/_brew_services

This PR proposes a new command that runs the service but doesn’t start it at login (nor boot).
It is based on the discussion in PR #87. 
Feedback is welcome.

Implement run command.

---

cmd/brew-services.rb

Documentation: Rephrase `brew services start|stop` usage

---

.travis.yml

If we check this at CI time it'll stop things getting out of sync.

Check Rubocop style

---

cmd/brew-services.rb

brew-services: tweak handling of "run" services.

---

cmd/brew-services.rb

Ideally we'd support this behaviour but I've been unable to come up with a good solution for this so for now present a better error message.
Fixes #130.

Don't fail to run services as root.

---

cmd/brew-services.rb

Correctly detect the user a service started as.

---

cmd/brew-services.rb

This also fixes a RuboCop style violation.

brew-services: move Homebrew checks to module.

---

completions/bash/_brew_services

Quick attempt to add bash completion for brew services. Not a bad starting point, maybe.

simple bash completion

---

LICENSE.txt
README.md
cmd/brew-services.rb

Improve these to go into Homebrew's manpage.

Update license and documentation.

---

README.md

The incorrect command was defined to remove all unused services

Corrected cleanup command in Readme

---

cmd/brew-services.rb

cmd/brew-services: fix brew style failures.

---

cmd/brew-services.rb

Format to match other docs and append colons to command specs.

Update services help text

---

azure-pipelines.yml
cmd/brew-services.rb

This is for better consistency with Homebrew's other commands.

brew-services: tweak help output.

---

cmd/brew-services.rb

This patch is related to https://github.com/Homebrew/brew/pull/5864 and fixes  https://github.com/Homebrew/brew/issues/5847

error when using brew services on linux

---

cmd/brew-services.rb

Make this consistent with Homebrew/brew in https://github.com/Homebrew/brew/pull/6036.

Add frozen_string_literal comment

---

cmd/brew-services.rb

This should avoid the executable being replaced for root escalation.

services: take root ownership when running as root.

---

cmd/brew-services.rb

There's a few more directories that we should ensure can't be replaced.

brew-services: chown/chmod more root paths.

---

cmd/brew-services.rb

Different format strings now required.

brew-services: fix brew style.

---

cmd/brew-services.rb

brew-services: handle missing ProgramArguments.

---

Gemfile
Gemfile.lock
cmd/services.rb
lib/services_cli.rb
spec/spec_helper.rb

This is consistent with `brew bundle` and allows cleaning up some code.

Make `brew services` run `brew services list`.

---

cmd/services.rb

This is more consistent with other commands (and will look better in a manpage).

cmd/services: tweak help output.

---

lib/services_cli.rb
spec/spec_helper.rb

These weren't being checked due to https://github.com/Homebrew/brew/pull/7253.

Fix `brew style` failures.

---

.github/workflows/tests.yml
lib/services_cli.rb

See also:
- https://github.com/Homebrew/brew/pull/7485
- https://github.com/Homebrew/homebrew-core/pull/54137
Fixes https://github.com/Homebrew/homebrew-services/issues/219
Closes https://github.com/Homebrew/homebrew-services/pull/220

services_cli: fix handling non-existent program_location.

---

.github/workflows/tests.yml

No longer needed after https://github.com/Homebrew/brew/pull/7510

workflows/tests: remove brew style cd.

---

lib/services_cli.rb

Love the custom plist support. This request is to extend the feature to the restart command. Took a long time to discover how to use custom plists. Happy to describe it in the documentation too, if you can point me to what doc files should be edited.

Enable custom_plist with restart

---

lib/service.rb

Use `any_version_installed`.
Fixes #224.

services: fix deprecation.

---

lib/service.rb
lib/services_cli.rb

Inspired by https://github.com/Homebrew/brew/issues/7641#issuecomment-633119625

Recommend root/non-root from Formula#plist_startup

---

lib/service.rb

For https://github.com/Homebrew/brew/pull/7677.

service: fix brew style.

---

spec/spec_helper.rb

See https://github.com/Homebrew/brew/pull/7867.

Fix brew style.

---

.github/workflows/tests.yml

workflows/tests: use actions/cache@main.

---

.github/workflows/tests.yml

This is needed to run RSpec tests.

workflows/tests: install Ruby.

---

lib/services_cli.rb

Needed for Homebrew/brew#8382.

lib/services_cli: require formula

---

lib/service.rb
lib/services_cli.rb

Needed for Homebrew/brew#8297.

lib: fix rubocop failures.

---

Gemfile
spec/stub/exceptions.rb

Needed for https://github.com/Homebrew/brew/pull/8542.

Fix RuboCop violations.

---

lib/service.rb

Fixes https://github.com/Homebrew/homebrew-services/issues/275

service: don't report error? with a valid PID.

---

completions/bash/brew-services

Prefix was not changed in all places in last PR, needing to fix.

fixing prefix

---

lib/service.rb
lib/services_cli.rb

Rename the function because it says very little about the start, but much more about a file being present

chore: rename `started?` to `plist_present?` to beter describe the function

---

lib/services_cli.rb

Brew itself doesn't support this anymore so it can be dropped.

chore: remove support pre-yosemite

---

lib/service.rb
spec/homebrew/service_spec.rb
spec/spec_helper.rb

Should fix https://github.com/Homebrew/homebrew-services/issues/345 that I caused yesterday

fix: resolve naming issues

---

lib/service.rb
lib/services_cli.rb
spec/homebrew/service_spec.rb

Also move the methods around to be:
1. helpers
1. commands
1. internal functions

chore: split large blocks into functions to help readability

---

lib/service.rb
lib/services_cli.rb
spec/homebrew/service_spec.rb

Fixes #349
Reverts Homebrew/homebrew-services#348

Revert "chore: split large blocks into functions to help readability"

---

.github/workflows/tests.yml

Adding a `restart` task to catch anything similar to #354 in the future :)
/cc @issyl0 @SMillerDev

Add restart task to test workflow

---

cmd/services.rb

Should fix https://github.com/Homebrew/discussions/discussions/1660

fix: correctly scope available_services

---

lib/services_cli.rb
spec/homebrew/services_cli_spec.rb
spec/spec_helper.rb

Simplify some functions and increase test coverage

chore: add simple tests for cli

---

.github/workflows/tests.yml
cmd/services.rb
lib/service.rb
lib/services_cli.rb
spec/homebrew/service_spec.rb
spec/homebrew/services_cli_spec.rb
spec/spec_helper.rb

I might still split some of this out further before attempting to merge. But this should allow @Homebrew/linux to use `brew services`

Service: add systemd support

---

lib/services_cli.rb

fix: reset @service_file at the end of the loop

---

lib/services_cli.rb

fix: install service file specified by --file

---

lib/service/services_cli.rb

services_cli: allow ps to return an empty line

---

cmd/services.rb
lib/service.rb
lib/service/formula_wrapper.rb
lib/service/formulae.rb
lib/service/services_cli.rb
lib/service/system.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/services_cli_spec.rb
spec/homebrew/system_spec.rb
spec/spec_helper.rb

Move all system utility functions to a new `System` class instead of polluting `ServicesCli`

Move system information to separate class

---

lib/service/commands/restart.rb

Fixes https://github.com/Homebrew/homebrew-services/issues/399
Fixes https://github.com/Homebrew/homebrew-bundle/issues/1023

fix: always start on restart

---

spec/spec_helper.rb

Fix the incorrect coverage and enable branch coverage checking

chore: exclude test directory from test coverage

---

lib/service/commands/cleanup.rb
lib/service/commands/list.rb
lib/service/formulae.rb
spec/homebrew/commands/cleanup_spec.rb
spec/homebrew/commands/list_spec.rb
spec/homebrew/commands/restart_spec.rb
spec/homebrew/formulae_spec.rb
spec/homebrew/system_spec.rb
spec/spec_helper.rb

Fixes:
- a misunderstanding in the cleanup command
- Filename at the end of the list
Closes #401

chore: improve tests for the commands

---

.github/workflows/tests.yml

Split actions into separate runs for `style`, `rspec` and functional tests

actions: split tests

---

lib/service/commands/list.rb
lib/service/formula_wrapper.rb
lib/service/formulae.rb
spec/homebrew/commands/list_spec.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/formulae_spec.rb
spec/stub/exceptions.rb

Also adds some tests for other wrapper functions

wrapper: add `to_hash` function for usage with JSON

---

lib/service/services_cli.rb

services_cli: fix `root?` module.

---

spec/homebrew/commands/list_spec.rb
spec/homebrew/commands/restart_spec.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/system_spec.rb

Done by `brew style --fix` for https://github.com/Homebrew/brew/pull/12937.

Fix RSpec style.

---

README.md

I took a stab at updating the readme to reflect the Linux systemctl support. This is related to #459.

Updated readme with linux info

---

lib/service/services_cli.rb

This PR is related to something that came up during [the review](https://github.com/Homebrew/homebrew-services/pull/464#discussion_r824053818) of the last one related to adding the kill command. Essentially, the previous kill function was renamed to launchctl_kill in ServicesCli to make room for the new method but it duplicated a lot of the functionality of the old one. This PR removes that method and then refactors the methods that called it.
1. #kill_orphaned_services
It was replaced by the new #kill method
2. #stop
It was replaced by the launchctl stop command
I also ended up refactoring the ServicesCli#stop method to remove the call to launchctl_kill and make it more consistent with documentation.
- remove unnecessary checks
- added a call to the systemctl disable command so that …

Removed #launchctl-kill and refactored #stop in services_cli.rb

---

cmd/services.rb
lib/service/commands/list.rb
lib/service/system.rb
spec/homebrew/system_spec.rb

For https://github.com/Homebrew/brew/pull/13433

Fix ENV style issues

---

spec/spec_helper.rb

For https://github.com/Homebrew/brew/pull/13671

spec/spec_helper: fix brew style.

---

lib/service/system.rb
spec/homebrew/system_spec.rb

Reverts Homebrew/homebrew-services#485

Revert "Added support for running services fully backgrounded on macOS"

---

lib/service/services_cli.rb
lib/service/system.rb
spec/homebrew/system_spec.rb

This fix https://github.com/Homebrew/homebrew-services/issues/434#issuecomment-1007484572

Add sudo support for systemctl

---

README.md

```
$ brew man
Error: Unknown command: man
$ man brew
[works]
```

README.md correct command

---

lib/service/formula_wrapper.rb
spec/homebrew/formula_wrapper_spec.rb

Companion PR to https://github.com/Homebrew/brew/pull/14371.

formula_wrapper: return hash if there is no service command

---

lib/service/formula_wrapper.rb

Related to Homebrew/brew#14528.

`brew style --fix`

---

cmd/services.rb

No idea why this has cropped up now. Feels like it's probably worth moving everything into the `Homebrew` module to avoid this mess.
Fixes https://github.com/Homebrew/homebrew-services/issues/562 (combined with https://github.com/Homebrew/brew/pull/15052)

cmd/services: scope Service class properly.

---

lib/service/formula_wrapper.rb
spec/homebrew/formula_wrapper_spec.rb

This now seems to be dead code.

formula_wrapper: remove generate_plist.

---

lib/service/formulae.rb

Fixes https://github.com/Homebrew/homebrew-services/issues/590

formulae: handle services or plists.

---

.github/workflows/tests.yml
README.md
lib/service/commands/info.rb
lib/service/commands/kill.rb
lib/service/commands/list.rb
lib/service/commands/restart.rb
lib/service/commands/run.rb
lib/service/commands/start.rb
lib/service/commands/stop.rb
lib/service/formula_wrapper.rb
lib/service/services_cli.rb
spec/homebrew/commands/list_spec.rb

For https://github.com/Homebrew/brew/pull/16848

Use RuboCop default hash syntax.

---

lib/service/system.rb

- When SSHing in: we can use the `gui` domain if the SSH session is as the same user as the logged-in GUI user.
- When running `brew services` when `uid` and `euid` do not match: we want to use the `user` domain instead of the `gui` domain.
Fixes #601

system: improve macOS SSH and EUID handling.

---

cmd/services.rb

I came across this command via https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/cmd/services_spec.rb , which is an unusual, cross-repo test. Let's see if this works.

Port command to use AbstractCommand

---

lib/service/formula_wrapper.rb
lib/service/formulae.rb
lib/service/services_cli.rb
spec/homebrew/formula_wrapper_spec.rb

lib/service: fix deprecations.

---

cmd/services.rb

Fixes https://github.com/Homebrew/homebrew-services/issues/696
Fixes https://github.com/Homebrew/homebrew-core/issues/177327

cmd/services: add missing require.

---

lib/service.rbi

As seemingly agreed on in https://github.com/Homebrew/homebrew-services/pull/711#discussion_r1722110918 but deferred for a separate PR?

service.rbi: remove

---

spec/homebrew/commands/list_spec.rb
spec/homebrew/formula_wrapper_spec.rb

For https://github.com/Homebrew/brew/pull/18828

various: swap `/dev/null` for `File::NULL`
