Homebrew/homebrew-services

cmd/brew-services.rb

If no plist is available throw an error (instead of writing an empty plist file).
CC @gapple @DomT4 @xu-cheng

Handle no plist.

---

cmd/brew-services.rb

```
cmd/brew-services.rb:183: syntax error, unexpected '.', expecting kEND
.map { |formula|  Service.new(formula) }
^
cmd/brew-services.rb:184: syntax error, unexpected '.', expecting kEND
.select { |service|  service.plist?  }
^
cmd/brew-services.rb:185: syntax error, unexpected '.', expecting kEND
.map { |service|
^
```

Fix compatibility with OSX 10.8 Mountain Lion and Ruby 1.8.7

---

cmd/brew-services.rb

Because `.opoo` returns `nil`, `return` was never executed because of the short circuit evaluation of `and`.
Example:
```Ruby
» a = []
» puts 'explode does not exist' and explode if a.empty?
explode does not exist
=> nil
» explode
NameError: undefined local variable or method `explode' for main:Object
from (pry):3:in `<main>'
```
This was the stack trace before:
```
Warning: No services available to control with `brew services`
Error: undefined method `[]' for nil:NilClass
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:207:in `list'
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:162:in `run!'
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:402:in `<top (required)>' …
```

Fix return if no services to control are available

---

cmd/brew-services.rb

This provides a convenient way of starting a service only if it wasn't already running and avoids using `restart`, parsing the output of `list`, or missing other important error messages when starting a service as part of an installation script.

Avoid failure exit mode if service already started

---

cmd/brew-services.rb

Hey,
This PR shouldn't change the existing behaviour, it just reduces the number of global variables used by passing target directly into the method. Also makes the `restart` method much nicer.
Notice the use of `Array(x)` vs `[x]`, these do not have the same effect. `Array(x)` won't wrap a passed in array, while `[x]` will do that:
```ruby
irb(main):001:0> Array(1) == Array([1])
=> true
irb(main):002:0> [1] == [[1]]
=> false
```

Refactor out the use of global variables

---

cmd/brew-services.rb

Provides a hint that the service is started as `root` or `user` when trying to stop it as `user` or `root` respectively.
Say `nginx` is starting on boot as `root`, when you do `brew services list`:
```
Name         Status  User Plist
nginx        started root /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
```
When you was executing `brew services stop nginx`, that was the output:
```
Error: Service `nginx` not running, wanna start it? Try `brew services start nginx`
```
Which is confusing because `nginx` is actually running, but as `root`.
After applying this patch, you will get this message:
```
Error: Service `nginx` not started as `capripot`, wanna start it? Try `brew services start nginx`
Service `nginx` is started as `root` tho, wanna stop it? Try `sudo brew services stop nginx` …
```

Add hint on stop

---

cmd/brew-services.rb

Error message should show reverse, as user: `sudo..`, and as root: not sudo

Hint message on stop is reversed

---

cmd/brew-services.rb

Newer hash syntax was not working for me under ruby 1.8.7 on OS X 10.8. See below:
```
Error: /usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:201: syntax error, unexpected ':', expecting ')'
if service.started?(as: :root)
^
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:205: syntax error, unexpected kELSIF, expecting kEND
elsif service.started?(as: :user)
^
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:205: syntax error, unexpected ':', expecting ')'
elsif service.started?(as: :user)
^
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:338: syntax error, unexpected kEND, expecting $end
/usr/local/Library/brew.rb:21:in `require'
/usr/local/Library/brew.rb:21:in `require?' …
```

Compatibility fix for ruby 1.8.7 under OS X 10.8 Mountain Lion

---

cmd/brew-services.rb

When running as root, you need to add the UserName key to the plist, however, the key is being added when running as local user, and not when running as root, causing almost (if not all) services to fail.

Invert logic for adding UserName to plist when running as root or not

---

README.md

Fixes typo in final example (`brew services start|stop|etc`) and adds an example to show users how to `brew services list` to confirm for anyone skimming that yes, said functionality is indeed there.

improve readme slightly

---

cmd/brew-services.rb

This is because `launchctl` gets upset about user attachments and very weird, hard-to-debug things happen. Note that we have a warning for this already in Homebrew. CC @xu-cheng

brew services cannot run under tmux.

---

.travis.yml
cmd/brew-services.rb

The shebang is no longer needed for this to be called by Homebrew and the argument handling is buggy and can be simplified by using `ARGV.named`.

Cleanup argument handling, remove shebang.

---

cmd/brew-services.rb

``` sh
$ brew services stop mongodb
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/Library/Taps/homebrew/homebrew-services/cmd/brew-services.rb:188:in `run!'
Stopping `mongodb`... (might take a while)
==> Successfully stopped `mongodb` (label: homebrew.mxcl.mongodb)
```

Formula.factory is deprecated

---

cmd/brew-services.rb

- clarify that `restart`, `start` and `stop` will restart one named service, unless used with `--all`
fixes #68
💜

Improve documentation of commands

---

completions/zsh/_brew_services

This addresses code that was lost from the changes to the completions
scripts from oh-my-zsh. It requires a change to brew to install
completion scripts, but can be manually tested before then via symlink:
```shell
ln -s /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/completions/zsh/_brew_services /usr/local/share/zsh/site-functions/_brew_services
```

Add zsh completions for brew-services

---

cmd/brew-services.rb

Previously their formula names meant that services could not be resolved through an over-strict regex.
Fixes https://github.com/Homebrew/homebrew-core/issues/7711.

Handle versioned formulae names.

---

cmd/brew-services.rb

This likely indicates a badly configured Homebrew `plist` but it's something that should be exposed to Homebrew contributors rather than users who find it confusing. CC @antstorm for thoughts and code review.

Make a missing PID "unknown" rather than "error".

---

cmd/brew-services.rb

I’ve found small bug in the newly implemented run command. This PR fixes it. Sorry for that.

Fix run --all command.

---

completions/zsh/_brew_services

This PR fixes the error ``_brew_services:88: parse error near `>'`` due unescaped single quote.
An alternative way is to use UTF apostrophe `’`.

Fix completion parse error

---

cmd/brew-services.rb

Without this additional check services could be detected as already running when they were actually just stopped. This prevented the plist file from being installed correctly.
Also, remove some undesirable whitespace.
Fixes #102.

Non-loaded services were not running.

---

cmd/brew-services.rb

As discussed in #111, convert to using `launchctl bootstrap` (preceded by `launchctl enable`) instead of the deprecated `launchctl load -w` form.
This gives us error reporting, which fixes #111. It also means we're not using a deprecated API, which is good.  And it also paves the way for better separation of root vs. user (e.g. so the same command need not do different things in those cases), and perhaps also to fix the problems of running launchctl under tmux/screen (maybe).
While we're here, document the `-v` flag, which was useful here. (Why doesn't the usage message standout in **bold** like in the builtin commands?)
Example of error detection we didn't have before:
```
bash-3.2# brew services -v run ntp
Unsetting PERL5LIB to protect you from yourself
/bin/launchctl enable …
```

Convert to using launchctl bootstrap instead of deprecated launchctl load -w

---

cmd/brew-services.rb

Just use `whoami` which is sufficient now we only support plists running as a single user.
Fixes #113.

brew-services: don't get the user from the Cellar.

---

.travis.yml
cmd/brew-services.rb

Use `launchctl`'s `kill` and `disable` subcommands rather than `unload` to avoid weirdness where services aren't properly terminated.
CC @bryanaknight who ran into this.

brew-services: use non-deprecated unload methods.

---

cmd/brew-services.rb

Files such as [~]/Library/LaunchDaemons/foobar.plist installed by
[sudo] brew services start foobar
ended up with overly restrictive 0600 permissions. While launchd
accepted this because it's not a security risk, other system daemons
run as non-root and need world-read on those files to work properly.

brew-services: follow Apple guidance for launchd plist file perms

---

cmd/brew-services.rb

The `bootout` command isn't implemented yet and `unbootstrap` does nothing.
CC @pavelrad to verify if this fixes the problem for you.
Fixes #124.

brew services stop: fix on Yosemite.

---

cmd/brew-services.rb

This opens a URL directly rather than potentially allowing process execution.

services: use explicit open.

---

LICENSE.txt

Clarify what the license is and use the same text as Homebrew itself.

LICENSE: fix licence detection.

---

cmd/brew-services.rb

I am not sure, but I seem to remember this being sorted before. I _think_ that on HFS+, directories always returned directory listing results in sorted order, but that changed on APFS. I had the same issue in another project of mine.

Sort "brew services list" based on service name

---

cmd/brew-services.rb

Currently, `brew services start --all` will stop processing once it encounters a service that is already started. This change enables `start --all` to start any remaining services. `stop --all` already does this.
Current behavior:
```
Name               Status  User   Plist
consul             stopped
couchdb            started stefan /Users/stefan/Library/LaunchAgents/homebrew.mxcl.couchdb.plist
elasticsearch@2.4  stopped
$ brew services start --all
/Users/stefan/Library/LaunchAgents/homebrew.mxcl.couchdb.plist: service already loaded
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/stefan/Library/LaunchAgents/homebrew.mxcl.couchdb.plist` exited with 133.
Name               Status  User   Plist
consul             started …
```

Avoid error for "start --all" when there already are services started

---

cmd/brew-services.rb

Ensure that we match the EOL character so we don't duplicate on e.g.
`mysql` and `mysql@5.7` both being available.
Fixes #194.

brew-services: tweak list grep.

---

cmd/services.rb

cmd/services: fix typo.

---

cmd/services.rb
lib/services_cli.rb
spec/homebrew/services_cli_spec.rb

Using colons before subcommand descriptions causes the man page output to indent them. Homebrew/brew#7393 applies the same effect to its `--help` output.

cmd/services: adjust help output

---

README.md
cmd/services.rb

This is included in `brew man`, `brew services --help` and is less likely to get outdated as a result.

README: move documentation to --help.

---

README.md

Anywhere we can use `blob/master` we can use `blob/HEAD` instead. This will make life easier if we ever rename our default branch in future (once/if Git and GitHub provides the necessary tooling to do so).

Refer to default branch in links with HEAD

---

lib/services_cli.rb

When using HomeBrew Services to stop a command originally run as `root`, a suggestion appears if `sudo` isn't specified.
Consider the following screenshot as an example:
As illustrated above, an accidental double quote is shown at the end of the status message `sudo brew services stop php@7.2"`.
This change proposes to fix the output of the message to omit the trailing quote.

Remove Unmatched Quote in HomeBrew Services CLI Message

---

completions/bash/brew-services

The existing shell completion only found plist files that had been started, which means you had to know the name of the service to start it. This changes it so only the `stop|cleanup` uses this.
Commands that run services (`start|restart|run`) now find services using:
`find "${BREW_PREFIX}/Cellar"  -mindepth 3 -maxdepth 3 -name 'homebrew.mxcl.*.plist'`.
Where BREW_PREFIX is set on shell startup as `brew --prefix` output.
Adds active services started with `sudo` to the completions as well.
On my machine calling `brew --prefix` adds ~30ms latency to shell startup, but no impact after that. If there's a better way to find that would love to know!
I have a version that gets rid of the duplicate string expressions but it was pretty difficult to grok, going with this instead for readability.

bash-completion: separate out running commands

---

lib/services_cli.rb

- retry `bootout` until the service is no longer `loaded?`
- sleep for one second instead of five and retry bootout more often
- clarify `unless` legacy logic
Fixes #284

services_cli: improve service restarts.

---

.github/workflows/tests.yml
lib/services_cli.rb

- When running `brew services` with a couple of services started as a normal user, and one service started as root, this was the output:
```
➜ brew services
Name       Status  User   Plist
mosquitto  started issyl0 /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
postgresql started   issyl0 /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
vault      error   root /Library/LaunchDaemons/homebrew.mxcl.vault.plist
```
- When running `sudo brew services` with the same combination of services, this was the output:
```
➜ sudo brew services
Password:
Name       Status  User Plist
mosquitto  started root /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
postgresql started root /Users/issyl0/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
vault …
```

services_cli: Fix list command wrongly showing root user as owner

---

lib/services_cli.rb

Now that we're actually tracking the PIDs of started processes I've stopped seeing "unknown" meaning "started and running but we've lost track of it somehow".
Cautiously, let's change the behaviour here to show the `unknown` state to all users (and roll back if we get complaints about breakage).

services_cli: always shown "unknown" state.

---

lib/service.rb
lib/services_cli.rb
spec/homebrew/service_spec.rb
spec/spec_helper.rb

This moves all functions to more explicit `system` calls. It also changes the status/error regex to read from the specific service page.

stop using backticks and grep

---

README.md
cmd/services.rb
lib/service.rb
lib/services_cli.rb
spec/homebrew/service_spec.rb
spec/homebrew/services_cli_spec.rb
spec/spec_helper.rb

Attempt number 2, this time making the `file` argument specific.
~Tests ❌, so it's a draft for now.~
This does drop support for specifying a Plist as a URL, but I don't think it makes sense to keep that option (and it can be easily solved with wget).

chore: split large blocks into functions to help readability

---

lib/services_cli.rb

- This was breaking `brew services restart`:
```
> brew services restart mysql@5.7
Error: wrong number of arguments (given 3, expected 1..2)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:212:in `start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:189:in `block in restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:181:in `restart'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:80:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```
/cc @SMillerDev as this changed in #353.
- Fixes https://github.com/Homebrew/brew/issues/11514.

lib/services_cli: Pass `verbose` kwarg to `start` method

---

lib/services_cli.rb
spec/homebrew/services_cli_spec.rb

- This was buggy such that a not running service without a PID would default to showing as "unknown". This is because the `service_get_status` method would never fall through to the `else` condition of `:stopped`.  It was always being caught by `service.unknown_status?` because there was no PID and `formula[:status]` was blank as it wasn't being set first of all.
- This fixes it such that `formula[:status]` starts off as `:stopped`, then we set it to `:started` if a PID exists, as we did before 44f7fc0aeb8f2e594caa5e1b6e3317d49ebbe8bd.
- Given we're only checking if the service is started or otherwise errored, I renamed `service_get_status` to `service_get_operational_status` as it was clearer to me.
- I removed the fallback test as there is no fallback - ":stopped" is a service's default …

lib/services_cli: Fix not-running service status always being "unknown"

---

completions/bash/brew-services

-----
Don't run `brew --prefix` if `$HOMEBREW_PREFIX` variable is already defined, improving shell startup time.

Don't invoke ruby if `$HOMEBREW_PREFIX` is already defined

---

lib/service/commands/list.rb
lib/service/formulae.rb
lib/service/services_cli.rb

Moves the command output generation into the command and cleans up the output better (file instead of plist and `~/` instead of `/Users/x/`

list: move logic to command

---

cmd/services.rb

Commit 7c4a420 moved the available_services class method from
Service::ServicesCli to Service::Formulae, but cmd/service.rb still
referred to the old class, causing a unknown method error.

fix: --all flag causing a unknown method `available_services` error

---

.github/workflows/tests.yml
cmd/services.rb
lib/service/commands/cleanup.rb
lib/service/commands/list.rb
lib/service/commands/restart.rb
lib/service/commands/run.rb
lib/service/commands/start.rb
lib/service/commands/stop.rb
lib/service/formulae.rb
lib/service/services_cli.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/services_cli_spec.rb
spec/spec_helper.rb
spec/stub/exceptions.rb

Always pass targets as an array, and always do all validations.
This also moves the restart logic and adds a bunch of tests, getting total coverage to 70% of the LOC

chore: always use service arrays

---

lib/service/services_cli.rb

While running `brew services cleanup` today, I got this stack trace:
```
brew services cleanup
launch          stale => killing service...
Error: undefined local variable or method `domain_target' for Service::ServicesCli:Module
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:168:in `kill'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:55:in `block in kill_orphaned_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:51:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:51:in `kill_orphaned_services'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/cleanup.rb:13:in `run' …
```

Prepend `System` to domain targets

---

lib/service/formula_wrapper.rb

Check if exit code is present before checking the value.

formula_wrapper: allow missing exit code

---

lib/service/commands/list.rb
spec/homebrew/commands/list_spec.rb
spec/spec_helper.rb

I noticed that in certain situation, `brew services list` doesn't property column-ify its output:
```console
Name      Status  User         File
mosquitto started rylanpolster ~/Library/LaunchAgents/homebrew.mxcl.mosquitto.plist
stubby    error  256 rylanpolster ~/Library/LaunchAgents/homebrew.mxcl.stubby.plist
unbound   none
znc       scheduled rylanpolster ~/Library/LaunchAgents/homebrew.mxcl.znc.plist
```
This is because it assumes that the longest possible status string is 7 characters. This is no longer true, though, since `scheduled` and `error 256` are both longer.
I rewrote the method that outputs these columns to check for the longest status column and pad every other item to that width. This is complicated a little bit by the color codes from `Tty.color` and …

Fix `brew services list` columns

---

cmd/services.rb

This makes clear that `start` and `run` are command literals, not action descriptions.
Addresses https://github.com/Homebrew/homebrew-core/issues/93285.

services: fix missing highlight

---

lib/service/commands/list.rb
spec/homebrew/commands/list_spec.rb

This avoids it being output when using `brew bundle` or other tools that parse `brew services` output.
Fixes #438

lib/service/commands/list: only output "no services" warning with TTY.

---

lib/service/services_cli.rb
spec/homebrew/services_cli_spec.rb

This is a one line fix for a bug in the implementation of the ServicesCli.start() function.
The code on line 89 used a reject statement which made the if statement starting on line 90 unreachable. I removed that. Additionally, I added test cases to make sure this works correctly in the ServicesCli.start() and ServicesCli.run() functions (the ServicesCli.run() function was already working correctly but lacked a test case).
Since this is a really small bug fix, I decided to just make PR instead of creating an issue. I hope that's okay.

Small bug fix for ServicesCli.start() function

---

README.md

This is the smallest PR ever created. It just removes the now unnecessary single quote from the readme as mentioned in [#460](https://github.com/Homebrew/homebrew-services/issues/459#issuecomment-1058923011) and [#459](https://github.com/Homebrew/homebrew-services/pull/460#discussion_r819339834). I kind of feel bad that the CI/CD pipeline is gonna run after I create this.

Removed unnecessary punctuation from readme

---

lib/service/services_cli.rb

Just a small loop bug that I found in the ServicesCli.kill() function.

Bug fix for loop that would never run more than once

---

.github/workflows/tests.yml
lib/service/formula_wrapper.rb
lib/service/services_cli.rb
spec/homebrew/services_cli_spec.rb

Okay, I think I figured it out. This is related to issue #469.
Basically, the linux and mac versions of the `brew services stop` command behaved differently in no small part because the ServicesCli#loaded? command was always returning true on linux.
Now both of them stop, unregister and unload the service. Before the linux services would stay loaded. This meant having to change the behavior of ServicesCli#service_load to install the systemctl service file if it doesn't exist which didn't happen before with the `brew services run` command.
And now the functional test workflow has been updated to reflect the fact that stopped services should return `service-name none` when using the `brew services list` command.

Make `brew services stop` behave the same on linux and mac

---

cmd/services.rb
lib/service/commands/restart.rb
lib/service/services_cli.rb
spec/homebrew/commands/restart_spec.rb
spec/homebrew/services_cli_spec.rb

This PR includes three things: additional warnings and usage errors, updated documentation, and a refactored restart command. The first two are pretty obvious from looking the code but the third one might not be so I'll explain it.
Essentially, the previous restart command called stop and then either start or run internally. The stop command always removes the service file. Then, the default generated service file is used to start up the service again. So essentially that custom service file would get overwritten with the default generated version which is not ideal. Instead, it now uses the internal systemctl and launchctl restart commands, which don't overwrite the service file, and defers to the start command if the service isn't loaded. Because that calls out to systemctl and …

Service file warnings and Restart Cmd Refactor

---

lib/service/commands/restart.rb
lib/service/services_cli.rb
spec/homebrew/commands/restart_spec.rb
spec/homebrew/services_cli_spec.rb

This restores the old restart command as discussed so that it can be used to update service files after upgrading formulas. I added a note to the `restart.rb` file mentioning the intended behavior but I'm not exactly sure how to add tests so this sort of thing doesn't happen again in the future.
The first thing that comes to mind would be to add a functional test that checks to make sure that the service file was updated/overwritten after the call to `brew services restart`. Finding a cross platform way to do that and reconciling the different locations of the services files on macOS and linux is probably beyond me to be honest.
Either way this PR should fix the immediate problem.

Restore old restart command

---

lib/service/services_cli.rb
lib/service/system.rb
spec/homebrew/system_spec.rb

This PR is the product of a discussion on the [main Homebrew repo](https://github.com/Homebrew/discussions/discussions/3253). In short: it aims to improve working with `brew services` on multi-user systems when sharing a global HB instance, although there is also some benefit for single-user systems (see the next section).
Besides changing the `gui/*` domain to `user/*` stuff, HB now also modifies every plist it installs (or checks if it has to, at least). I've explained that last part in comments next to the relevant code, so I'm not going to repeat it here. It's not a very large patch anyway. :> The `user` domain seems to always be present as long as some form of login occurred, it can also co-exist with `gui`. And since `homebrew-services` is specifically meant for **background** …

Added support for running services fully backgrounded on macOS

---

cmd/services.rb

Pass along the `XDG_RUNTIME_DIR` so systemctl --user can fall back to it's
internal dbus socket; needed when no user-session dbus daemon is installed.
Depends on Homebrew/brew#13686 to be merged for `HOMEBREW_XDG_RUNTIME_DIR` to
exist.
Fixes #496

systemd: support systemctl --user without dbus

---

lib/service/services_cli.rb
spec/homebrew/services_cli_spec.rb

fixes brew trying to call kill with a bunch of strings when orphaned services are found

pass services instead of labels to ServicesCli#kill

---

.github/workflows/tests.yml

`redis` installation is failing on macOS runner recently: https://github.com/Homebrew/homebrew-services/actions/runs/3936224646/jobs/6736004244 + it is very heavy. Let's switch to `consul` that is a one-bottle-download, which means faster tests.
Also update the container image used for tap syntax job to 22.04.

workflows: ubuntu 16.04->22.04 and redis->consul

---

completions/bash/brew-services

Previously, `__brewcomp_prev` function was provided in Homebrew/brew Bash completion script. It was removed in Homebrew/brew#14545 because no other function in Homebrew/brew was using it. Since Bash completions for Homebrew/services relies on this function, we restore `__brewcomp_prev` here.
Addresses Homebrew/homebrew-services#549

Bash completions: add __brewcomp_prev

---

completions/zsh/_brew_services

Currently, trying to get completion for `brew services` results in `a completion function is not defined for command or alias: services` and no actual completions. This is because `#compdef brew` in _brew_services conflicts with an identical statement in _brew, causing Zsh's compinit to not load _brew_services at all.
This commit fixes that by instead declaring that this file defines completion for `brew services` only.

Fix Zsh completion

---

cmd/services.rb
lib/service/commands/list.rb
lib/service/formula_wrapper.rb
lib/service/formulae.rb
lib/service/services_cli.rb
lib/service/system.rb
spec/homebrew/commands/list_spec.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/services_cli_spec.rb
spec/spec_helper.rb

When running `brew services` over `ssh` or `sudo` as a non-`root` user the `gui` domain target for `launchd` does not work as expected. This produces confusing failures for users.
It was tried before to detect if this was needed from the `.plist` or changing globally but both approaches were unsuccessful/error-prone.
Instead, use the `user` domain automatically on the cases we know it's needed: when running over `ssh` or through `sudo`. To make clear to users what's happening in these cases: output a warning (which can be hidden with an output environment variable).
For this to work, `launchctl list` is no longer sufficient. The output here, even when run as `root`, does not properly list `user` domain services. Instead, we need to use `launchctl print` to correctly query the status of …

Support (and set) `launchd` user domain target

---

cmd/services.rb
lib/service/formula_wrapper.rb
lib/service/services_cli.rb

This flag allows setting the `UserName` for `launchd` plists when running as `root`. This means that `launchd` will drop privileges to the relevant user when starting the service.
This is significantly more secure than running services as `root` and enables a reasonable way to run systemwide services as unprivileged users.

Add `--sudo-service-user` flag

---

cmd/services.rb
lib/service/commands/restart.rb
lib/service/commands/stop.rb
lib/service/services_cli.rb

This prevents us from looping and waiting for `brew services stop` to finish stopping the service if we just want to attempt once and immediately exit.
While we're here, also fix verbose output for `brew services restart`.

Add `--no-wait` argument

---

lib/service/services_cli.rb

These places were not changed correctly.

services_cli: fix usage of `systemctl_args` with `--no-block`.

---

lib/service/formula_wrapper.rb
lib/service/services_cli.rb

REXML is disappearing in Ruby 3 and will move to Homebrew/brew's Gemfile. At this time there are no plans to commit it to the repository as a vendored gem and `brew services` should work without needing to install any extra gems. `plist` is however already there as a committed vendored gem so we can use that. It also has better API.
I haven't tested the `--sudo-service-user` part of this. @MikeMcQuaid you're likely best positioned to test that.

Use `plist` over `rexml`

---

cmd/services.rb
lib/service/commands/restart.rb
spec/homebrew/commands/restart_spec.rb

`UsageError` is the same as `odisabled` in this case.
Probably should be merged at the same time as 4.2.0 is released, though the error is well overdue so I'm fine with whenever really.

Disable `brew services restart --file=`

---

lib/service/formula_wrapper.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/services_cli_spec.rb
spec/homebrew/system_spec.rb

https://github.com/Homebrew/brew/pull/16338

Fix various style issues under newer RuboCop

---

cmd/services.rb
lib/service/formulae.rb

This changes how `--all` behaves. When stopping all services, it filters out the services that are already stopped, and vice versa when starting all services.
My motivation for this change is that I have `dnscrypt-proxy` installed which causes `brew services stop --all` to no longer work properly and stop halfway through.
```
Name           Status  User   File
caddy          none           
dnscrypt-proxy none    root   
grafana        started stefan ~/Library/LaunchAgents/homebrew.mxcl.grafana.plist
$ brew services stop --all
Warning: Service `caddy` is not started.
Error: Service `dnscrypt-proxy` is started as `root`. Try:
sudo brew services stop dnscrypt-proxy
Name           Status  User   File
caddy          none           
dnscrypt-proxy none …
```

Improve behavior of `--all`

---

cmd/services.rb

This is the version required for `AbstractCommand` to work.

cmd/services: note when Homebrew is too old.

---

.github/workflows/tests.yml

`shellcheck` is reporting [SC2046](https://www.shellcheck.net/wiki/SC2046) (Quote this to prevent word splitting) and [SC2086](https://www.shellcheck.net/wiki/SC2086) (Double quote to prevent globbing and word splitting) issues in the `tests.yml` workflow. Adding quotes in affected areas resolves these warning/info messages but I haven't tested these changes, so take this with a grain of salt.
Related to https://github.com/Homebrew/brew/pull/17482

Fix style issues

---

.github/workflows/stale-issues.yml

Pin the version of the actions to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

workflows: pin actions

---

cmd/services.rb

The slash separating the two paths is easily confused for another path
separator. Let's make it less ambiguous by using something that isn't
also a path separator.

cmd/services: improve help text

---

cmd/services.rb

If this is set to the e.g. `>=4.3.0 (shallow or no git repository)` string, work harder to actually extract the version number from it.

cmd/services: better handle HOMEBREW_VERSION.

---

lib/service/commands/cleanup.rb
lib/service/commands/info.rb
lib/service/commands/kill.rb
lib/service/commands/list.rb
lib/service/commands/restart.rb
lib/service/commands/run.rb
lib/service/commands/start.rb
lib/service/commands/stop.rb
lib/service/formulae.rb
lib/service/services_cli.rb
lib/service/system.rb
spec/spec_helper.rb

Should help #711 if CI passes
These modules should be called as `Service::Whatever.method` and never via `include Service::Whatever`, so remove `module_function` to forbid the latter and get stronger typing as a result.

Drop unnecessary module_function

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock
cmd/services.rb
cmd/services.rbi
lib/service.rb
lib/service.rbi
lib/service/commands/cleanup.rb
lib/service/commands/info.rb
lib/service/commands/kill.rb
lib/service/commands/list.rb
lib/service/commands/restart.rb
lib/service/commands/run.rb
lib/service/commands/start.rb
lib/service/commands/stop.rb
lib/service/formula_wrapper.rb
lib/service/formulae.rb
lib/service/services_cli.rb
lib/service/system.rb
spec/spec_helper.rb

- I thought I'd use this as a test bed for https://github.com/Homebrew/brew/pull/18027. Now we have a minimal successful Sorbet typed tap.

Basic Sorbet `typed: true`

---

lib/service/formula_wrapper.rb
lib/service/services_cli.rb
lib/service/system.rb
lib/service/system/systemctl.rb
spec/homebrew/formula_wrapper_spec.rb
spec/homebrew/services_cli_spec.rb
spec/homebrew/system/systemctl_spec.rb
spec/homebrew/system_spec.rb
spec/spec_helper.rb
spec/stub/system_command.rb

When EUID != UID, `systemctl` basically ignores any environment variable and is largely nonfunctional.
`system_command` has handling to support this so wrap `systemctl` calls to make use of that.

Improve handling of systemctl under mixed UID environments

---

cmd/services.rb
cmd/services.rbi
lib/service/commands/stop.rb
lib/service/services_cli.rb

We currently only have a choice between passing `--no-wait` or omitting
it. In the former, we don't wait at all for services to stop. In the
latter, we wait as long as it takes (which could be forever, if some
services have frozen for some reason).
This enables a middle ground where we wait only up to a given amount of
time until we're no longer willing to wait for a service to stop.
Will probably needs tests.

Add `--max-wait` flag for `stop` subcommand

---

cmd/services.rb

- Part of https://github.com/Homebrew/brew/issues/17297, as this was easy.

Bump `cmd` files to Sorbet `typed: strict`

---

cmd/services.rb

This is consistent with e.g. https://github.com/Homebrew/brew/pull/19153

cmd/services: use `${HOME}` instead of `~`

---

cmd/services.rb

Reverts Homebrew/homebrew-services#890
See https://github.com/Homebrew/brew/pull/19153#discussion_r1930678587

Revert "cmd/services: use `${HOME}` instead of `~`"
